### ISSUE TITLE
How to append modules (custom components) to the ui?

### ISSUE THREAD

**Issue by mepsoid** [haxeui/haxeui-core#120]
[Modules documentation](https://github.com/haxeui/haxeui-guides/blob/master/modules.md) says that in order to use custom classes in xml markup I should use file `module.xml` with node `components`. But `Macros` class of haxeui library doesn't load file `module.xml` as it's code fragment is commented.

Then I tried to use `ComponentClassMap.register(...)` method but this doesn't help too. When I compile sources haxeui macro says `C:/HaxeToolkit/haxe/lib/haxeui-core/git/haxe/ui/macros/ComponentMacros.hx:131: WARNING: no class found for component: board`.

Are custom components with short xml aliases working?

**Comment by ianharrigan** [comment]
So there are a few times modules (and custom components) can be loaded (although it will only actually load the modules once), the place it all really happens is: https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/macros/ModuleMacros.hx#L177. Thought this of course gets called for you. 

Any chance you can zip up a minimal test case? Will be easier to diagnose then.

Cheers,
Ian

The macros set of classes are pretty messy currently as there is actually two versions there, so the older version needs to be refactored out. But in essence any `module.xml` is loaded from the class path and t

**Comment by mepsoid** [comment]
Here's an example
[haxeui-component-test.zip](https://github.com/haxeui/haxeui-core/files/860504/haxeui-component-test.zip)

**Comment by ianharrigan** [comment]
Ok, so there are a couple of things:

1) the `module.xml` wasnt on the classpath, it was in `/assets/ui` - moving it to `/src/test` was needed to expose it to the macro (ie, put it in the classpath).

2) the `module.xml` wasnt correct (in didnt contain a root `<module>` node, i changed it to this:
```xml
<module>
    <components>
        <class name="test.CustomComponent" alias="cc" />
    </components>
</module>
```    
3) there was some mix a match of module mark up (`<components/>` node) in the `test.xml` though i presume that was just to test? Just to be clear, its totally fine to have anything in the `test.xml` but it will try to be interpreted as a component, so leaving that mark there results in "components not found" type thing as it things components is a component. 

Fixing those things makes it work fine. 

Also, side note: the reason why `ComponentClassMap.register("cc", "test.CustomComponent")` didnt work is because that is essentially run at runtime and `ComponentMacros.buildComponent` build the component at compile time so it isnt in the registry at that stage, ill have think about it and see if there is a way to make that work.

**Comment by mepsoid** [comment]
Thanks, it works now.
