### ISSUE TITLE
DialogButton.ID should be an Int?

### ISSUE THREAD

**Issue by tienery** [haxeui/haxeui-core#18]
I'm curious why `ID` is a string, when on lines [58-98](https://github.com/haxeui/haxeui-core/blob/master/haxe/ui/containers/dialogs/DialogOptions.hx#L58-L98) of `DialogOptions` set the `id` of each standard button with an Integer, but as a string. From a performance perspective, matching strings is slower than matching integers.

Take the following example code:

```haxe
private static function showBasicDialog(view:Component, onOk:Function = null)
{
	var options = new DialogOptions();
	options.addStandardButton(DialogButton.OK);
	options.addStandardButton(DialogButton.CANCEL);

	Screen.instance.showDialog(view, options, function(b:DialogButton) {
		if (b.id == '${DialogButton.OK}')
		{
			if (onOk != null)
				onOk();
		}
	});
}
```

It wouldn't affect many of the comparisons, but for `YES` and `NO` there's two character comparisons instead of one since they're two digits in size.

**Comment by ianharrigan** [comment]
This is because the DialogButton will eventually turn into a Button and that has a id of type String. The reason is because you may want to add non-standard buttons to your dialog and give them an id of, say, "myDialogButton", you can then use that later:

```haxe
Screen.instance.showDialog(view, options, function(b:DialogButton) {
    if (b.id == 'myDialogButton') {
       ...
    }
});
```

And the reason why DialogButton id is an int to start with is to keep compatibility with wxWidgets and also allow bitwise operations, eg: `DialogButton.YES | DialogButton.NO`

Also, the performance you are talking about is certainly negligible in your example. User clicks a button then the code "b.id == 'xyx'" is run. The code 'b.id == 123' would certainly be faster, but again, in this example, its not a loop, or anything really except a single user action.
