### ISSUE TITLE
[new-component-method] Multiple Questions

### ISSUE THREAD

**Issue by hoseyjoe** [haxeui/haxeui-core#284]
In the attached JS project I am flailing! I dont understand width=100% or height=100%.  I think that it should mean that the object takes 100% of what the parent gives it.

1. "Lang" and "support@Byteme.com" buttons are intended to be on the top right of the screen
2. "A Button 1111" and "Button 2222" are accordions and I expected that clicking the text would open them.  Accordions appear to only open with triangle button.  Looking at code it looks like they are made as buttons...but IDK.
3. ContinuousHBox with id "thebox" has content that doesn't wrap because it doesn't have a specified width.  Giving 100% width to parents doesn't appear to work...I would like to have it fill available space and then wrap.
4. Button with text "Bottom?"; I was hoping it would appear bottom left.
[sample.zip](https://github.com/haxeui/haxeui-core/files/3269797/sample.zip)

Sorry I dont understand better

**Comment by ianharrigan** [comment]
So this is interesting, there is a difference / discrepancy between `ComponentMacros.createInstance` and `ComponentMacros.buildComponent`... i havent had a full look but certainly if you use createInstance you get different results. 

1. 'hbox1' needs to be 100% width, it also shouldnt be an hbox... if you want to horizontal align, use a vbox or a box. Im not sure halign makes sense on an hbox... table maybe, but not an hbox, eg:

```xml
<hbox width="100%">
    <button text="left" />
    <button text="right" horizontalAlign="right" />
</hbox>
```

vs

```xml
<box width="100%">
    <button text="left" />
    <button text="right" horizontalAlign="right" />
</box>
```

thats as far as ive got so far, will look at the rest tomorrow, but there is certainly something off with createInstance. 

Thanks for the find! 

Ian

**Comment by ianharrigan** [comment]
Ok, ive fixed createInstance now, so that should be able to be used again and get the same results as buildComponent. So for the others:

1. as mentioned, the top hbox (hbox1) wasnt 100% width, if you make its background color, say, red, you'll see what i mean. So making that 100% width will mean it will take up 100% of its parents (the top level vbox) which is also 100% so, the hbox will take up the whole screen. As for aligning the last 2 buttons to the right. You have two options:

    * use a box rather than a hbox, im not sure horizontalAlign means much on an hbox... I have been thinking about this though, and it i might add it in, just not 100% sure yet, and it doesnt exist at the moment

    * use a spacer... you can put an spacer between the first and last hbox and set it to 100% width (personally, i would use a box rather than an hbox):

```xml
<hbox width="100%">
    <button />
    <spacer width="100%" />
    <button />
</hbox>
```

2. I think you _may_ be using accordion wrong, an accordion is a component and its children are the pages, you have actually wanted to two accordions on your page, but the fact that they were named "page1" and "page2" makes me thing otherwise, this is basic accordion:

```xml
<accordion>
    <box text="Page 1">
        <button text="Content 1" />
    </box>
    <box text="Page 2">
        <button text="Content 2" />
    </box>
</accordion>
```

That said, there issue with the accordion was that it didnt have a width, setting it to fixed width or a % width fixed the issue (if you use a % width, ofc you have to make sure its parents are using either a fixed or % width - ie, not autosized). I have a think about the accordion and getting it to autosize based on contents, if not at least, a default size wouldnt hurt


3. ContinuousHBox will grow its height when it "overflows", however, you fixed its height at 100%... thus essentially negating this. The way to use it to is to give it a fixed (or %) width, and let the height grow as its needs too. In your example, i removed the `height:100%` from the ContinuousHBox, added a `width=100%` to it, and also added a `width=100%` to the parent hbox (so the ContinuousHBox can use % width) 

4. This is basically the same as #1 except its a vbox and valign (rather than hbox and halign), again, i might add this to the layouts, but im not 100% sure it makes sense to do so yet, so the same applies as with #1 (ie, either use a box instead of the parent vbox, or use a 100% height spacer). One thing i did notice is the vbox you wanted on the bottom had `verticalAlign='bottom'` _and_ `height=100%`. This makes me think you might have misunderstood the alignment in the layouts, it doesnt mean "align my children to the bottom" it means "align _me_ to the bottom" (hence saying "make me 100% height and align me to the bottom" doesnt really make sense in this context. (Ofc saying "make me 50% height and align me to the bottom" does make sense, and other times 100% does also, but since i noticed it it made me thing that make you thought the children were aligned, not the component that has the tag - i could be wrong).

A little long winded, but hopefully this makes a little sense and clears up some of the issues / understanding? Ive also included the "revised" version of the xml using the principles mentioned above, which is what i _think_ you were going for - let me know if this helps any! 

Cheers,
Ian

**Comment by ianharrigan** [comment]
```xml
<vbox width="100%" height="100%" style="padding: 5px; ">
    <box width="100%" id="hbox1" style="___background-color: red;">
		<hbox>
			<button id="btn1" text="Click Me!" onclick="this.text='Thanks!'"/>
			<button text="File" onclick="this.text='Thanks!'"/>
			<button text="Reports" onclick="this.text='Thanks!'"/>
			<button text="Administration" onclick="this.text='Thanks!'"/>
			<button text="Messages" onclick="this.text='Thanks!'"/>
		</hbox>
		<hbox horizontalAlign="right" >
			<button text="Lang" onclick="this.text='Thanks!'" horizontalAlign="right"/>
			<button style="horizontalAlign:right" text="Support@Byteme.com" onclick="this.text='Thanks!'" horizontalAlign="right"/>
		</hbox>
	</box>
	<hbox width="100%" style="height:100%;">
		<box style="width:300px; height:100%;___background-color: yellow;">
			<tabview style="width:300px;background-color:#00ff00">
				<vbox text="Pre-Analysis" width="100%"  >
					<accordion width="100%" icon="haxeui-core/styles/default/haxeui_tiny.png">
						<box text="Page 1" style=" background-color:#00ff33" onclick="this.text='Thanks!'">
							<button text="Click Me!" onclick="this.text='Thanks!'"/>
						</box>
						<box text="Page 2">
                            <button text="Button 2" />
                        </box>    
					</accordion>    
				</vbox>
				<vbox text="Analysis"></vbox>
				<vbox text="Post-Analysis"></vbox>
			</tabview>
			<vbox verticalAlign="bottom">
				<button  text="Bottom?" onclick="this.text='Thanks!'"/>
			</vbox>
		</box>
		<ContinuousHBox width="100%" id="thebox" style="___background-color: green;" >
			<!--<dropdown width="82" height="25" text="DropDown" horizontalAlign="right" verticalAlign="bottom"/>
			<textfield width="150" text="TextField" horizontalAlign="center"/>
			<horizontalslider width="150" pos="0" min="0" max="100" verticalAlign="bottom"/>
			<horizontalprogress width="150" height="20" max="100" horizontalAlign="right"/>
			<spacer width="0" height="0"/>-->
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<image resource="haxeui-core/styles/default/haxeui.png"/>
			<absolute style="height:100%;verticalAlign:bottom">
				<button  text="Random" onclick="this.text='Thanks!'"/>
			</absolute>
		</ContinuousHBox>
	</hbox>
	
</vbox>
```

![image](https://user-images.githubusercontent.com/3024242/59181919-b28dae00-8b68-11e9-8d4a-72289251147d.png)

**Comment by ianharrigan** [comment]
Can this be closed?

**Comment by hoseyjoe** [comment]
sorry yes
