### ISSUE TITLE
Getting 84 errors on 1st attempt. Does anyone have a clue what am I missing?

### ISSUE THREAD

**Issue by VishwasGagrani** [haxeui/haxeui-core#309]
## Expected Behavior

I am getting a list of errors on using haxeui. 

## Media

![haxeui-errors](https://user-images.githubusercontent.com/294382/68105432-82262200-ff04-11e9-9c0a-7d2b39ab2fdd.png)

## Your Environment

* Version used: 1.8.21 Haxeui
* Environment name and version (e.g. Chrome 39, node.js 5.4):  Html5 Firefox
* Operating System and version (desktop or mobile): 
Windows 10
* Link to your project:
[buttons.zip](https://github.com/haxeui/haxeui-core/files/3802978/buttons.zip)

**Comment by ianharrigan** [comment]
Hi!

Ok, so the issue here is that you are using an old version of haxeui, one that is no longer supported / updated. https://github.com/ianharrigan/haxeui.

The repo (the one for this issue) is the "new" version of haxeui. As such you need to use a different set of haxelibs. First, use "haxeui-core" (this repo) for the core framework, then you need to choose a "backend", i can see you are using openfl, so for you it would be "haxeui-openfl". Then try that again.

Let me know if that clears up any confusion!

Cheers,
Ian

**Comment by ianharrigan** [comment]
Looking at your project there are also some other issues with both the way you are setting up openfl and the way you are using haxeui, attached is your fixed project. 
[buttons-fixed.zip](https://github.com/haxeui/haxeui-core/files/3803216/buttons-fixed.zip)

Hope that helps!

Cheers,
Ian

**Comment by VishwasGagrani** [comment]
Thank you for your time. I will look into the code let you know if I still face issue.

**Comment by ianharrigan** [comment]
Im going to close this issue now.
