### ISSUE TITLE
Clicking on row with chekcbox in tableview and listview changes values

### ISSUE THREAD

**Issue by karliss** [haxeui/haxeui-core#328]
## Expected Behavior
Clicking on an item in listview or tableview doesn't affect checkboxes unless checkbox was directly clicked. Clicking on checkbox doesn't affect other checkboxes.

## Current Behavior
Clicking on an item causes all other checkboxes to be temporary unchecked and the one in selected line to be checked similar to radio button group. If the list is sufficiently long scrolling down and up restores original values.

## Steps to Reproduce (for bugs)
http://www.haxeui.org/explorer/ - listview example
1. Click on add "100k virtual items"
2. click on item with empty checkbox not the checkbox itself
3. observe that checkboxes in all lines except selected one get unselected
4. scroll down
5. scroll up and observe that checkbox values have returned to original values

Table example behaves similar to listview  http://haxeui.org/builder/?pjyxyt

## Test app / minimal test case
See links in steps to reproduce

## Your Environment

* Version used:
* Environment name and version:  80.0.3987.87 
* Operating System and version (desktop or mobile): Linux

**Comment by ianharrigan** [comment]
OK, this should be fixed in latest git now.

This is was a pretty "fun" one actually. So actually the data was totally fine, what was happening is when select a table row it was adding ":selected" to all components under it and removing ":selected" from all others. Well, ":selected" is also shared by checkbox / optionbox, etc. It wasnt actually needed, i only needed to add/remove ":selected" for ItemRenderers.

Anyway, fixed now, can you close this issue if you are happy. 

Cheers,
Ian

(ps: im also going to update the explorer and builder on the site).
