### ISSUE TITLE
Button CSS cannot remove icon

### ISSUE THREAD

**Issue by Shallowmallow** [haxeui/haxeui-core#386]
## Test app / minimal test case

If we apply some css to  button
             .button {
                icon: none;
            }
            .button:down {
                icon: "haxeui-core/styles/default/down_arrow.png"
            }

## Expected Behavior
When the button is toggled, the icon should appear.  When the button is not pressed, the icon should disappear.
( It should work like the checkbox);

## Current Behavior
When the button is toggled, the icon appears, but it never disappears

## Possible Solution
Don't know yet.

## Context
I want to show a warning icon , when a button is toggled.

## Is it urgent, important ?
No, I can use code instead. I just noticed the issue, that's I posted it :)

**Comment by ianharrigan** [comment]
Ok this should be fixed now... Found a small little bug kinda relating to this too where even if you "null" the icon it will still think its in the layout (since the icon was never actually removed, just its resource was set to null)... thats also fixed now.

Cheers,
Ian

![button-icon-1](https://user-images.githubusercontent.com/3024242/123213348-330c7680-d4c6-11eb-9f65-de658bfddda3.gif)
