### ISSUE TITLE
ListView has UNSELECTABLE row after adding/removing row several times using CUSTOMITEMRENDERER

### ISSUE THREAD

**Issue by hypergeome** [haxeui/haxeui-core#393]
I have a listview.
The list has both selectable and unselectable rows.
I use CustomItemRenderer that inherits from ItemRenderer.
I make row selectable/unselectable by setting this.disableInteractivity(true/false, true, true); base on row data (override updateValues function in my custom itemrenederer class).
Then, I add/removing rows on the list and somehow, the list rows behave wrong on selectable/unselctabe, i.e. some rows should be selectable but not and some rows should be unselectable but not.
I am not sure how to fix this.
## Expected Behavior

There should be a way to make this usecase works. 

## Possible Solution

Currently, I have to recreate the listview everytime updating list data
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by ianharrigan** [comment]
Do you have a minimal test app that displays the issue? Also what happens if you .disable rather than .disableInteractivity?

**Comment by hypergeome** [comment]
I tried with .disabled. It is the same. But here, I need disableInteractivity so that when mouse hovering over row, it wont be disaplyed as selecting.

Here you go.

It is an opnefl project created using HaxeDevelop.
[DemoListBug.zip](https://github.com/haxeui/haxeui-core/files/6621560/DemoListBug.zip)

You can compile and run it and see that there are disabled and enabled rows. It works correctly.
But then, you can try adding disabled and enabled row and you will see the wrong behavior.

**Comment by ianharrigan** [comment]
Thanks for the test app. So actually, i think the problem is deeper and something to do with the data source / list view - you add, rather than insert, all seems fine... and when ive got the haxe to spit out the internal contents of the data source, then they dont make sense...

**Comment by ianharrigan** [comment]
Actually, scratch that, i _think_ the issue is in `disableInteractivity`, it basically keeps a counter of how many times things have been enabled / disabled... ... well, the "issue" is that things are reused in the listview, so that internal state is wrong

**Comment by ianharrigan** [comment]
OK, so that should be working now - ive added _another_ param to `disableInteractivity` (force=false)... if you set this to true it will essentially reset the internal counter and "force" the disable / enable. For now you will have to set that manually in your custom itemrenderer while i think of a way (or if its even worth it) to have listview automatically reset interactivity when its data changes (since this is somewhat of an edge case i think manual way of doing things is fine). 

Also, just to understand, is there any reason you extended your `ListDemoRenderer` from `CustomItemRenderer` which looks to be a copy of `ItemRenderer` with some parts commented out (show()  etc). I went back to using `ItemRenderer` to test (just to see) and it all works fine without. Im mainly just asking as maybe there are other issues you have encountered? 

Anyways, fix should be in latest git version of haxeui-core, lemme know if that fixes it for you and if you are happy to close this...

Cheers,
Ian

![listview](https://user-images.githubusercontent.com/3024242/121311582-d5dcc680-c904-11eb-8d4c-29f49cee8a8d.gif)


Just for completeness, this is what i changed your custom renderer to (just added the 4th param to `disableInteractivity` and extended from `ItemRenderer`:

```haxe
class ListDemoRenderer extends ItemRenderer
{

	public function new() 
	{
		super();
	}
	private override function updateValues(value:Dynamic, fieldList:Array<String> = null) {
		if (null != value){
			if(value.item == MainView.DISABLED_TEXT){
				this.disableInteractivity(true, true, true, true);
			}else{
				this.disableInteractivity(false, true, true, true);
			}
		}
		super.updateValues(value, fieldList);
	}
}
```

**Comment by hypergeome** [comment]
Thank you very much. It works. Cheers!!!
